# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ['win-x64', 'linux-x64', 'osx-x64']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --runtime ${{ matrix.runtime }} --self-contained false

      - name: Rename Binary
        run: |
          mkdir Release
          if [[ "${{ matrix.runtime }}" == "win-x64" ]]; then
          mv vsmodtools/bin/Release/net7.0/${{ matrix.runtime }}/publish/vsmodtools.exe Release/vsmodtools-${{ matrix.runtime }}.exe
          else
          mv vsmodtools/bin/Release/net7.0/${{ matrix.runtime }}/publish/vsmodtools Release/vsmodtools-${{ matrix.runtime }}
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vsmodtools-${{ matrix.runtime }}
          path: "**/bin/Release/net7.0/${{ matrix.runtime }}/publish/"

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release/publish/vsmodtools-linux-x64
            Release/vsmodtools-osx.x64
            Release/vsmodtools-win-x64.exe

permissions:
  contents: write