# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ['win-x64', 'linux-x64', 'osx-x64']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --runtime ${{ matrix.runtime }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vsmodtools_testing-${{ matrix.runtime }}
          path: "**/bin/Release/net7.0/${{ matrix.runtime }}/publish/"

  release:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vsmodtools/bin/Release/net7.0/linux-x64/publish/vsmodtools
            vsmodtools/bin/Release/net7.0/win-x64/publish/vsmodtools.exe
            vsmodtools/bin/Release/net7.0/osx-x64/publish/vsmodtools
